
name: sspcd
channels:
  - defaults
  - pytorch=1.9.0
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - scipy
  - tqdm
  - h5py
  - jupyterlab
  - matplotlib
  - json
  - pillow
  - glob2
  - argparse
  - open3d
  - tensorboardX
  - future-fstrings
  - easydict
  - joblib
  - scikit-learn
  - datetime